// Pilot payload schema for the canonical event envelope (ADR-0017).
//
// This is the first non-envelope schema registered in
// proto/registry.json and exercises the per-payload pattern that
// ADR-0018 establishes: each event type lives under
// proto/<family>/v<n>/<name>.proto with a `go_package` pointing
// to the corresponding location under
// internal/shared/contracts/<family>/v<n>/.
//
// See PROGRAM-0002 (Fase Wire) for the delivery roadmap.
//
// Status (per proto/registry.json): draft.
// This schema has no runtime consumer yet; promotion to "stable"
// status happens when an `ingest` adapter publishes trade events
// wrapped in the canonical envelope in production (future phase
// after Fase Wire).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: marketdata/v1/trade.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TradeV1 carries a single executed trade. Used as payload for
// envelopes whose `type` is "marketdata.trade" and whose
// `version` is 1.
//
// Timestamps are NOT carried here — the canonical envelope
// (ADR-0017) carries ts_exchange and ts_ingest as envelope-level
// fields. Including them in the payload would duplicate state
// and risk drift between envelope and payload time stamps.
type TradeV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Execution price (quote-asset units per one base-asset unit,
	// venue-normalized). Stored as double; precision concerns of
	// floating-point arithmetic are the consumer's responsibility
	// (typical consumers convert to decimal at the domain boundary).
	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	// Executed quantity (base-asset units, venue-normalized).
	// Like `price`, stored as double; precision converted at the
	// consumer's domain boundary if needed.
	Quantity float64 `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// True when the buyer side was the aggressor (took liquidity);
	// false when the seller was the aggressor. Encodes the side of
	// the trade as a boolean rather than as a string (e.g.,
	// "buy"/"sell") because every venue the foundry sources from
	// can report this as a binary fact (Binance reports
	// `isBuyerMaker` which inverts to `buyer_is_taker`; other
	// venues report side string which converters normalize).
	BuyerIsTaker bool `protobuf:"varint,3,opt,name=buyer_is_taker,json=buyerIsTaker,proto3" json:"buyer_is_taker,omitempty"`
	// Venue-provided numeric trade identifier. Encoded as int64
	// for the venues the foundry supports today (Binance Spot
	// and Binance Futures both emit numeric IDs). If a future
	// venue emits non-numeric trade IDs, a new payload version
	// (TradeV2 with `string trade_id`) is added per ADR-0017
	// versioning rules.
	TradeId       int64 `protobuf:"varint,4,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeV1) Reset() {
	*x = TradeV1{}
	mi := &file_marketdata_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeV1) ProtoMessage() {}

func (x *TradeV1) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeV1.ProtoReflect.Descriptor instead.
func (*TradeV1) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeV1) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeV1) GetBuyerIsTaker() bool {
	if x != nil {
		return x.BuyerIsTaker
	}
	return false
}

func (x *TradeV1) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

var File_marketdata_v1_trade_proto protoreflect.FileDescriptor

const file_marketdata_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x19marketdata/v1/trade.proto\x12\rmarketdata.v1\"\x83\x01\n" +
	"\aTradeV1\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12$\n" +
	"\x0ebuyer_is_taker\x18\x03 \x01(\bR\fbuyerIsTaker\x12\x19\n" +
	"\btrade_id\x18\x04 \x01(\x03R\atradeIdJ\x05\bd\x10\xc8\x01B)Z'internal/shared/contracts/marketdata/v1b\x06proto3"

var (
	file_marketdata_v1_trade_proto_rawDescOnce sync.Once
	file_marketdata_v1_trade_proto_rawDescData []byte
)

func file_marketdata_v1_trade_proto_rawDescGZIP() []byte {
	file_marketdata_v1_trade_proto_rawDescOnce.Do(func() {
		file_marketdata_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_v1_trade_proto_rawDesc), len(file_marketdata_v1_trade_proto_rawDesc)))
	})
	return file_marketdata_v1_trade_proto_rawDescData
}

var file_marketdata_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_marketdata_v1_trade_proto_goTypes = []any{
	(*TradeV1)(nil), // 0: marketdata.v1.TradeV1
}
var file_marketdata_v1_trade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketdata_v1_trade_proto_init() }
func file_marketdata_v1_trade_proto_init() {
	if File_marketdata_v1_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_v1_trade_proto_rawDesc), len(file_marketdata_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketdata_v1_trade_proto_goTypes,
		DependencyIndexes: file_marketdata_v1_trade_proto_depIdxs,
		MessageInfos:      file_marketdata_v1_trade_proto_msgTypes,
	}.Build()
	File_marketdata_v1_trade_proto = out.File
	file_marketdata_v1_trade_proto_goTypes = nil
	file_marketdata_v1_trade_proto_depIdxs = nil
}
