package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNormalizeForComparison(t *testing.T) {
	input := `// This is a comment
func Foo() {
	// another comment
	return "bar" // inline
}
`
	got := normalizeForComparison(input)
	want := "func Foo() {\nreturn \"bar\"\n}"
	if got != want {
		t.Errorf("normalizeForComparison:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestCompareWithGolden_Pass(t *testing.T) {
	dir := t.TempDir()
	golden := filepath.Join(dir, "test.golden")
	if err := os.WriteFile(golden, []byte("func Foo() {\n\treturn 1\n}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	generated := "// generated by codegen\nfunc Foo() {\n\treturn 1\n}\n"
	result, err := CompareWithGolden(generated, golden)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Pass {
		t.Errorf("expected PASS, got FAIL with diffs: %v", result.Diffs)
	}
}

func TestCompareWithGolden_Fail(t *testing.T) {
	dir := t.TempDir()
	golden := filepath.Join(dir, "test.golden")
	if err := os.WriteFile(golden, []byte("func Foo() {\n\treturn 1\n}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	generated := "func Bar() {\n\treturn 2\n}\n"
	result, err := CompareWithGolden(generated, golden)
	if err != nil {
		t.Fatal(err)
	}
	if result.Pass {
		t.Error("expected FAIL, got PASS")
	}
	if len(result.Diffs) == 0 {
		t.Error("expected diffs, got none")
	}
}
