#!/usr/bin/env bash
#
# scripts/validate-commit-msg.sh
#
# Validates commit message format against the project's conventional
# commits convention. Called by lefthook's commit-msg hook.
#
# Adopted in P3.4 of Phase 3 (environment hardening).
#
# Accepted types: feat, fix, chore, docs, ci, refactor, test, style,
#                 perf, build, revert
# Accepted scope (optional): lowercase, alphanumerics, hyphens, dots
#                            (covers patterns like p3.4, scripts, ci)
#
# Examples:
#   feat: add new feature
#   fix(parser): handle empty input
#   chore(p3.4): adopt lefthook
#   docs(security): clarify policy
#
# Bypass: `git commit --no-verify` or `LEFTHOOK=0 git commit`

set -euo pipefail

COMMIT_MSG_FILE="${1:-.git/COMMIT_EDITMSG}"

if [ ! -f "$COMMIT_MSG_FILE" ]; then
    echo "ERROR: commit message file not found: $COMMIT_MSG_FILE" >&2
    exit 2
fi

# Read first line only (subject)
SUBJECT=$(head -1 "$COMMIT_MSG_FILE")

# Allow merge commits (auto-generated by git)
if [[ "$SUBJECT" =~ ^Merge ]]; then
    exit 0
fi

# Allow revert commits with default format
if [[ "$SUBJECT" =~ ^Revert ]]; then
    exit 0
fi

# Conventional commit regex
# Pattern: type(scope)?: description
# - type: required, lowercase
# - scope: optional, in parentheses
# - colon-space separator
# - description: any text (length validation separate)
PATTERN='^(feat|fix|chore|docs|ci|refactor|test|style|perf|build|revert)(\([a-z0-9._-]+\))?: .+'

if [[ ! "$SUBJECT" =~ $PATTERN ]]; then
    echo "❌ Invalid commit message format."
    echo ""
    echo "Subject was:"
    echo "  $SUBJECT"
    echo ""
    echo "Expected format:"
    echo "  type(scope?): description"
    echo ""
    echo "Accepted types: feat, fix, chore, docs, ci, refactor, test, style, perf, build, revert"
    echo ""
    echo "Examples:"
    echo "  feat: add new component"
    echo "  fix(parser): handle nil input"
    echo "  chore(p3.4): adopt lefthook"
    echo ""
    echo "Bypass (only when truly necessary):"
    echo "  git commit --no-verify"
    exit 1
fi

# Subject length warning (not blocking)
if [ ${#SUBJECT} -gt 72 ]; then
    echo "⚠️  Subject line is ${#SUBJECT} characters (>72)."
    echo "    Consider shortening for readability in tools like 'git log --oneline'."
    # Don't fail; just warn.
fi

exit 0
