// Canonical event envelope for events on the 11 JetStream streams.
//
// See ADR-0017 (event envelope and versioning) for the architectural
// decision. See PROGRAM-0002 (Fase Wire) for the delivery roadmap.
//
// Status (per proto/registry.json): draft.
// This schema is stable in shape but has no runtime consumer yet;
// promotion to "stable" status happens when a stream uses the
// envelope in production (future phase).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: envelope/v1/envelope.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps every domain event flowing through the foundry's
// JetStream mesh. It carries the nine canonical fields defined by
// ADR-0017: type, version, venue, instrument, ts_exchange,
// ts_ingest, seq, idempotency_key, payload.
//
// Coexistence: the legacy transport envelope at
// internal/shared/envelope/ continues to serve in-cluster RPC
// (commands, requests, replies) and is NOT retired by ADR-0017.
// The migration of the 11 streams from the legacy envelope to
// this canonical envelope is execution of the architectural
// decision and occurs in a future phase (see ADR-0017 erratum
// 2026-05-25).
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable event type identifier (e.g., "observation.trade",
	// "evidence.candle"). Type names are stable; a renamed event
	// type is a new event type. See ADR-0017 → "Versioning rules".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Schema version of payload. Breaking changes to payload shape
	// increment this field per ADR-0017. Consumers MUST support
	// version N and N-1 during active migration windows.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Canonical venue identifier (e.g., "binance", "binancef",
	// "bybit"). See ADR-0021 (canonical instrument and venue model)
	// for the enum values; promoted to Accepted in Onda H-6.
	Venue string `protobuf:"bytes,3,opt,name=venue,proto3" json:"venue,omitempty"`
	// Canonical instrument identifier (string form). Format chosen
	// for forward compatibility with ADR-0021's
	// CanonicalInstrument.Symbol() method: "{BASE}/{QUOTE}-{CONTRACT}".
	// Examples: "BTC/USDT-spot", "BTC/USDT-perpetual",
	// "BTC/USD-coinfutures".
	//
	// Venue is NOT embedded here (it lives in the `venue` field
	// above). When ADR-0021 is promoted to Accepted in Onda H-6,
	// this field MAY be replaced by a structured CanonicalInstrument
	// message; the string form was chosen to make that migration
	// a drop-in replacement (string form already equals the output
	// of the planned Symbol() method).
	Instrument string `protobuf:"bytes,4,opt,name=instrument,proto3" json:"instrument,omitempty"`
	// Exchange-provided timestamp in epoch nanoseconds. Absent
	// when the venue does not provide one or for synthetic events.
	// Uses `optional` to distinguish genuine absence from the
	// literal value 0 (epoch 1970-01-01T00:00:00Z), removing the
	// zero-as-sentinel ambiguity that a bare int64 carries.
	//
	// Consumers MUST NOT use ts_exchange for ordering, dedup, or
	// windowing — those use `seq` per ADR-0017 and ADR-0019
	// (deterministic replay invariant INV-D2). ts_exchange is
	// advisory only.
	TsExchange *int64 `protobuf:"varint,5,opt,name=ts_exchange,json=tsExchange,proto3,oneof" json:"ts_exchange,omitempty"`
	// Local timestamp at the moment the event crossed the ingest
	// binary's process boundary, in epoch nanoseconds. Always
	// present (sourced from the clock.Clock port per ADR-0019
	// INV-D1; never bypassed). Authoritative for TTL, telemetry,
	// and operational reasoning.
	TsIngest int64 `protobuf:"varint,6,opt,name=ts_ingest,json=tsIngest,proto3" json:"ts_ingest,omitempty"`
	// Monotonic sequence per stream key
	// `(venue, instrument, event_type)` produced by the Sequencer
	// (ADR-0020). Within a stream key, seq(n+1) > seq(n) always.
	// The canonical ordering authority — consumers MUST order by
	// seq, not by either timestamp.
	Seq int64 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	// Stable deduplication key derived from
	// (venue, instrument, type, seq). Survives transport-level
	// redelivery and consumer retries. The exact hash algorithm
	// and encoding are H-3.b implementation choices; the key MUST
	// be deterministic per ADR-0019 INV-D3 (replay produces
	// byte-identical output).
	IdempotencyKey string `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Versioned payload, encoded per the wire format of ADR-0018.
	// Decoder dispatches on (type, version) from this envelope
	// plus the wire codec signaled at the envelope level. Empty
	// bytes is a valid payload only when the event type's schema
	// explicitly defines it.
	Payload       []byte `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *Envelope) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Envelope) GetTsExchange() int64 {
	if x != nil && x.TsExchange != nil {
		return *x.TsExchange
	}
	return 0
}

func (x *Envelope) GetTsIngest() int64 {
	if x != nil {
		return x.TsIngest
	}
	return 0
}

func (x *Envelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_envelope_v1_envelope_proto protoreflect.FileDescriptor

const file_envelope_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1aenvelope/v1/envelope.proto\x12\venvelope.v1\"\x9d\x02\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x14\n" +
	"\x05venue\x18\x03 \x01(\tR\x05venue\x12\x1e\n" +
	"\n" +
	"instrument\x18\x04 \x01(\tR\n" +
	"instrument\x12$\n" +
	"\vts_exchange\x18\x05 \x01(\x03H\x00R\n" +
	"tsExchange\x88\x01\x01\x12\x1b\n" +
	"\tts_ingest\x18\x06 \x01(\x03R\btsIngest\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayloadB\x0e\n" +
	"\f_ts_exchangeJ\x05\bd\x10\xc8\x01B'Z%internal/shared/contracts/envelope/v1b\x06proto3"

var (
	file_envelope_v1_envelope_proto_rawDescOnce sync.Once
	file_envelope_v1_envelope_proto_rawDescData []byte
)

func file_envelope_v1_envelope_proto_rawDescGZIP() []byte {
	file_envelope_v1_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_v1_envelope_proto_rawDesc), len(file_envelope_v1_envelope_proto_rawDesc)))
	})
	return file_envelope_v1_envelope_proto_rawDescData
}

var file_envelope_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envelope_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: envelope.v1.Envelope
}
var file_envelope_v1_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envelope_v1_envelope_proto_init() }
func file_envelope_v1_envelope_proto_init() {
	if File_envelope_v1_envelope_proto != nil {
		return
	}
	file_envelope_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_v1_envelope_proto_rawDesc), len(file_envelope_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_v1_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_v1_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_v1_envelope_proto_msgTypes,
	}.Build()
	File_envelope_v1_envelope_proto = out.File
	file_envelope_v1_envelope_proto_goTypes = nil
	file_envelope_v1_envelope_proto_depIdxs = nil
}
